### PR TITLE
enhancement: Added support for Moshi

### PR DESCRIPTION
**Pull request by The-inside-man**
## Summary
- Add Moshi json parser support to gradle build

As requested by several customers

## Test plan
- FSC
- Verify Build

## Issues
- "OASIS-8052"
- [ISSUE-391](https://github.com/optimizely/java-sdk/issues/391)

### CODE REVIEW

**Review by jaeopt — CHANGES_REQUESTED** [review]
Don't we need to add ProjectConfig parser for Moshi? It must be much more expensive to add the support :)

**Comment by The-inside-man** [comment]
> d ProjectConfig parser fo

Ahh yes you may be right! haha Let me look at that! thank you for pointing that out!

**Comment by The-inside-man** [comment]
> Don't we need to add ProjectConfig parser for Moshi? It must be much more expensive to add the support :)

Ahh yes you may be right! haha Let me look at that! thank you for pointing that out!

**Comment by The-inside-man** [comment]
Closing PR for now as will need to be worked and backlogged appropriately.

**Pull request closed without merging**
