### PR TITLE
[FSSDK-8110] chore: add sample log4j config to demo app

### PR DESCRIPTION
**Pull request by jaeopt**
## Summary
Add log4j2 dependencies and lo4j2.properties for log-level control in Example app.

## Test plan
Pass existing tests

## Issues
- FSSDK-8110

### CODE REVIEW

**Review by mnoman09 — APPROVED** [review]
Overall changes lgtm, but I remember we removed it due to vulnerability is this version safe from that vulnerability?

**Comment by mikechu-optimizely** [comment]
@jaeopt I happened to see this PR. Do you still want it?

I think the version you're implementing is 👍 based on this [CISA notice](https://www.cisa.gov/news-events/news/apache-log4j-vulnerability-guidance)

**Comment by jaeopt** [comment]
Yes, as long as log4j version is 2.15.0 or higher, they can use it. And this sample configuration will be helpful. @muzahidul-opti

**Review by muzahidul-opti — APPROVED** [review]
LGTM

**Pull request merged**
