### PR TITLE
Refactor ProjectConfig to Abstract Class

### PR DESCRIPTION
**Pull request by wangjoshuah**
@optimizely/fullstack-devs

### CODE REVIEW

**Comment by mikeng13** [comment]
test this out

**Comment by caitlinrubin-optimizely** [comment]
test this please

**Comment by caitlinrubin-optimizely** [comment]
build

**Comment by caitlinrubin-optimizely** [comment]
build

**Comment by caitlinrubin-optimizely** [comment]
build

**Comment by caitlinrubin-optimizely** [comment]
build

**Comment by caitlinrubin-optimizely** [comment]
build

**Comment by caitlinrubin-optimizely** [comment]
build

**Comment by wangjoshuah** [comment]
will not need this since datafile changes will be additive only

**Pull request closed without merging**
